[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "env && npm run build-preview"

[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/news"
  status = 200
